// automatically generated by the FlatBuffers compiler, do not modify

package edu.gatech.cog.ipglasses.cog;

@Suppress("unused")
class Juror private constructor() {
    companion object {
        const val JurorA: Byte = 0
        const val JurorB: Byte = 1
        const val JurorC: Byte = 2
        const val JuryForeman: Byte = 3
        val names : Array<String> = arrayOf("JurorA", "JurorB", "JurorC", "JuryForeman")
        fun name(e: Int) : String = names[e]
    }
}
