// automatically generated by the FlatBuffers compiler, do not modify

package edu.gatech.cog.ipglasses.cog;

@SuppressWarnings("unused")
public final class Juror {
  private Juror() { }
  public static final byte JurorA = 0;
  public static final byte JurorB = 1;
  public static final byte JurorC = 2;
  public static final byte JuryForeman = 3;

  public static final String[] names = { "JurorA", "JurorB", "JurorC", "JuryForeman", };

  public static String name(int e) { return names[e]; }
}

